### ISSUE TITLE
Travis doesn't work with codesourcery compiler

### ISSUE THREAD

**Issue by kirkscheper** [tudelft/opencv_bebop#6]
Since e99d9b747364da70d237d12ea2784797b576ceea the code hasn't passed the CI tests. I don't think this is the idea to ignore the results of the CI tests so this needs updating.

**Comment by dewagter** [comment]
OK, I fixed master by reverting to the last working version.

The question is: will paparazzi master also use this codesourcery compiler. If it does, I'll set opencv back to codesourcery, but if master will not use it, then we better keep opencv working with that one.

@OpenUAS this also has to do with the pull request of wilco's code.

**Comment by dewagter** [comment]
Fixed: all are compiling: https://travis-ci.org/tudelft/opencv_bebop/branches
